name: Build

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - run: cargo install cargo-bump
    - uses: mrquentin/cargo-bump@main
    - name: Commit and push new version
      env:
        CI_COMMIT_MESSAGE: "[ci skip] Bump Version"
        CI_COMMIT_AUTHOR: CI Agent
      run: |
        git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
        git config --global user.email "username@users.noreply.github.com"
        git commit -a -m "${{ env.CI_COMMIT_MESSAGE }}"
        git push
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
