name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: mrquentin/commit-commands@v1.1
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
