on:
  workflow_dispatch:
  release:
    types: [published, created, edited]

name: Publish

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: publish
          args: --token ${{ secrets.CRATES_TOKEN }}
        env:
          CARGO_TOKEN: ${{ secrets.CRATES_TOKEN }}